require("core.options")
require("core.keymaps")
require("plugins.plugins-setup")
require("plugins.nvim-tree")
require("plugins.treesitter")
-- require("plugins.clangd")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.formatter")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.gitsigns")
require("plugins.telescope")
